//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CourseworkRepImpl.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class CourseworkRepImpl extends CourseworkRep {
    public void write(Connection conn, ArrayList list, int ref){
        
        try {   
                Statement st = conn.createStatement();
                ResultSet rs=null;
                for (int i = 0; i < list.size(); i++){
                    String sql = "UPDATE CUSTOMER SET CUST_ADDRESS ='" + ((Customer)list.get(i)).getAddress() + "' WHERE CUST_REF =" + ((Customer)list.get(i)).getRef() + "";
                    st.executeUpdate(sql);
                }
                    st.close();
        } catch (SQLException ex) {
                    System.out.println("SQLException error ");
        } 
    } 
    
    public ArrayList read(Connection conn){
        ArrayList list = new ArrayList();
        try {   
                Statement st = conn.createStatement();
                ResultSet rs=null;
                    String sql = "SELECT * FROM CUSTOMER";
                    rs=st.executeQuery(sql);
   
                while(rs.next()){ 
                    Customer cust = new Customer();
                    cust.setRef(rs.getInt("cust_ref"));
                    cust.setName(rs.getString("cust_name"));
                    cust.setAddress(rs.getString("cust_address"));
                    cust.setClaim(rs.getFloat("claim"));
                    cust.setQuote(rs.getFloat("quote"));
                    list.add(cust);
                    System.out.println(rs.getInt("cust_ref")+"\t"+rs.getString("cust_name")+
                            "\t"+rs.getString("cust_address")+"\t"+rs.getFloat("claim")+"\t"+rs.getFloat("quote"));
                }
                    rs.close();
                    st.close();
        } catch (SQLException ex) {
                    System.out.println("Connect failed ! ");
        } 
        
        customers = list;
        return customers;
    }
}   

}
