//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coursework.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Coursework {
	private Object courseworkNumber;
	private Object courseworkTitle;
	private Object dueDateAndTime;
	private IndividualOrGroup assessmentType;
	public void getCourseworkNumber() {
	
	}
	
	public void getCourseworkTitle() {
	
	}
	
	public void getDueDateAndTime() {
	
	}
	
	public void getAssessmentType() {
	
	}
}
