//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CourseworkRep.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public interface CourseworkRep {
	public void addCourseworkNumber();
	public void updateCourseworkNumber();
	public void addCourseworkTitle();
	public void updateCourseworkTitle();
	public void addDueDateAndTime();
	public void updateDueDateAndTime();
	public void addAssessmentType();
	public void updateAssessmentType();
}
