
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cover sheet.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Cover sheet {
	private Object uniqueReferenceNumber;
	private Object issueDate{
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
        System.out.println(dateFormat.format(date)); //2016/11/16 12:08:43
}
	private Object module;
	private Object coursework;
	private Object student;
}
