//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cover sheet list.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Cover sheet list {
	private Object list;
	public void addNewCvsheet() {
	
	}
	
	public void deleteCvsheet() {
	
	}
	
	public void findCvsheet() {
	
	}
}
