//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModuleRepImpl.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class ModuleRepImpl extends ModuleRep {
}
