//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ModuleRep.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public interface ModuleRep {
	public void addModuleCode();
	public void updateModuleCode();
	public void addModuleTitle();
	public void updateModuleTitle();
	public void addModuleTutor();
	public void updateModuleTutor();
	public void add%OfModuleMark();
	public void update%OfModuleMark();
}
