//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Module.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Module {
	private Object moduleCode;
	private Object moduleTitle;
	private Object moduleTutor;
	private Object %OfModuleMark;
	public void getModuleCode() {
	
	}
	
	public void getModuleTitle() {
	
	}
	
	public void getModuleTutor() {
	
	}
	
	public void get%OfModuleMark() {
	
	}
}
