//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student Controller.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Student Controller {
	public void generateCoverSheet() {
	
	}
}
