//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentUI.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class StudentUI {
	public void inputDetails() {
	
	}
	
	public void downloadCoverSheet() {
	
	}
}
