//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentRepImpl.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class StudentRepImpl extends StudentRep {
}
