//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentRep.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public interface StudentRep {
	public void addStudentName();
	public void updateStudentName();
	public void addStudentId();
	public void updateStudentId();
}
