//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.java
//  @ Date : 18/11/2016
//  @ Author : 
//
//




public class Student {
	private Object studentName;
	private Object studentId;
	public void getStudentName() {
	
	}
	
	public void getStudentId() {
	
	}
}
