//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoInt.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfoInt {
	public interger CourseWorkNo = 0;
	public interger IssueDate = 01012000;
	public interger dueDate = 01012000;
	public interger PerofMod = 0;
	public interger getCourseWorkNo() {
	
	}
	
	public void setCourseWorkNo(interger aCourseworkno) {
	
	}
	
	public interger getIssueDate() {
	
	}
	
	public void setIssueDate(interger aIssueDate) {
	
	}
	
	public interger getDueDate() {
	
	}
	
	public void setDueDate(interger aDueDate) {
	
	}
	
	public interger getPerofMod() {
	
	}
	
	public void setPerofMod(interger aPerofMod) {
	
	}
}
