//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfo.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfo { //this is the code to create an instance of the info for string methods
	public String Modulecode = "";
	public String ModuleTitle = "";
	public String ModuleTutor = "";
	public String CourseWorkTitle = "";
	public String AssessmentType = "";
        public int ID = 0;
	
        
        public String getModuleCode() {//get code returns the variable
	return Modulecode;
	}
	
	public void setModuleCode(String aModulecode) { //set code sets variables
	Modulecode = aModulecode;
	}
	
	public String getModuleTitle() {
	return ModuleTitle;
	}
	
	public void setModuleTitle(String aModuletitle) {
	ModuleTitle = aModuletitle;
	}
	
	public String getModuleTutor() {
	return ModuleTutor;
	}
	
	public void setModuleTutor(String aModuletutor) {
	ModuleTutor = aModuletutor;
	}
	
	public String getCourseWorkTitle() {
	return CourseWorkTitle;
	}
	
	public void setCourseWorkTitle(String aCourseworktitle) {
	
	}
	
	public String getAssessmentType() {
	return AssessmentType;
	}
	
	public void setAssessmentType(String aAssessmentType) {
	AssessmentType = aAssessmentType;
	}
        public void setID(int aID){
            ID = aID;
        }
        public int getID(){
            return ID;
        }
}
