//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoRepoImpl.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//


import java.util.ArrayList;

public class CourseWorkInfoRepoImpl extends CourseWorkInfoRepo {
      private ArrayList<CourseWorkInfo> CourseWorkInfo;
     
     public ArrayList<CourseWorkInfo> getAllCourseWork(){
        return CourseWorkInfo; 
    } 

}
