//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfo.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfo {
	public String Modulecode = "";
	public String ModuleTitle = "";
	public String ModuleTutor = "";
	public String CourseWorkTitle = "";
	public String AssessmentType = "";
	
        
        public String getModuleCode() {
	return Modulecode;
	}
	
	public void setModuleCode(String aModulecode) {
	Modulecode = aModulecode;
	}
	
	public String getModuleTitle() {
	return ModuleTitle;
	}
	
	public void setModuleTitle(String aModuletitle) {
	ModuleTitle = aModuletitle;
	}
	
	public String getModuleTutor() {
	return ModuleTutor;
	}
	
	public void setModuleTutor(String aModuletutor) {
	ModuleTutor = aModuletutor;
	}
	
	public String getCourseWorkTitle() {
	return CourseWorkTitle;
	}
	
	public void setCourseWorkTitle(String aCourseworktitle) {
	
	}
	
	public String getAssessmentType() {
	return AssessmentType;
	}
	
	public void setAssessmentType(String aAssessmentType) {
	AssessmentType = aAssessmentType;
	}
}
