//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoInt.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfoInt {//this is the code to create an instance of the info for Int methods
	public int CourseWorkNo = 0;
	public int IssueDate = 01012000;
	public int dueDate = 01012000;
	public int PerofMod = 0;
        public int ID = 0;
	
        public int getCourseWorkNo() { //get returns the methods
	return CourseWorkNo;
	}
	
	public void setCourseWorkNo(int aCourseworkno) {//set sets the variables
	CourseWorkNo = aCourseworkno;
	}
	
	public int getIssueDate() {
	return IssueDate;
	}
	
	public void setIssueDate(int aIssueDate) {
	IssueDate = aIssueDate;
	}
	
	public int getDueDate() {
	return dueDate;
	}
	
	public void setDueDate(int aDueDate) {
	dueDate = aDueDate;
	}
	
	public int getPerofMod() {
	return PerofMod;
	}
	
	public void setPerofMod(int aPerofMod) {
	PerofMod = aPerofMod;
	}
        public void setID(int aID){
            ID = aID;
        }
        public int getID(){
            return ID;
        }
        
        }

