//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoRepo.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//


import java.util.ArrayList;

public class CourseWorkInfoRepo {

public interface MemberRepo { //a repository to allow the data to be persistance, as the database was never implimeneted due to time this only serevrs to line to repoimpl

    
     
     public ArrayList<CourseWorkInfoInt> getAllCourseWorkInt();
        

     
     public ArrayList<CourseWorkInfo> getAllCourseWork();

        public void addCourseWork (CourseWorkInfo CW);
        public void addCourseWorkInt (CourseWorkInfoInt CW);
        public CourseWorkInfo getCourseWork(int ID);
        public CourseWorkInfoInt getCourseWorkInt(int ID);
}
}
