//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoRepoImpl.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//


import java.util.ArrayList;

public class CourseWorkInfoRepoImpl extends CourseWorkInfoRepo { //way to save the  inforamtion, for now in an array but in the future in a database. The code is designed to be called in pairs i.e. both gets code
      private ArrayList<CourseWorkInfo> CourseWorkInfos;
      private ArrayList<CourseWorkInfoInt> CourseWorkInfoInts; //init the arrays

     public ArrayList<CourseWorkInfoInt> getAllCourseWorkInt(){//retreves all coursework Int
        return CourseWorkInfoInts; 
        
    } 
     
     public ArrayList<CourseWorkInfo> getAllCourseWork(){ // gets all CourseWork string
        return CourseWorkInfos; 
        
    } 
         public void addCourseWork (CourseWorkInfo CW){  //adds a coursework info
        CourseWorkInfos.add(CW); 
    } 
        public void addCourseWorkInt (CourseWorkInfoInt CW){ //adds a course work int
        CourseWorkInfoInts.add(CW); 
    }
        public CourseWorkInfo getCourseWork(int ID){ //these two get a specific coursework
        return CourseWorkInfos.get(ID); 
    }
        public CourseWorkInfoInt getCourseWorkInt(int ID){ 
        return CourseWorkInfoInts.get(ID); 
    }
        public void updateCourseWorkInfo(CourseWorkInfo CW){ //not yet implimented But would allow changes in coursework

    }
          public void updateCourseWorkInfoInt(CourseWorkInfoInt CW){ 

    }
    
    public void deleteCourseWorkInt(CourseWorkInfoInt CW){ //deletes a coursework int and the other course info
            CourseWorkInfoInts.remove(CW.getID());
            System.out.println("CourseWork ID: "+ CW.getID()+ "deleted");
    }
        
    public void deleteCourseWork(CourseWorkInfo CW){ 
            CourseWorkInfoInts.remove(CW.getID());
            System.out.println("CourseWork ID: "+ CW.getID()+ "deleted");
    }
}