//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfo.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfo {
	public string Modulecode = "";
	public string ModuleTitle = "";
	public string ModuleTutor = "";
	public Object CourseWorkTitle string = "";
	public string AssessmentType = "";
	public string getModuleCode() {
	
	}
	
	public void setModuleCode(string aModulecode) {
	
	}
	
	public string getModuleTitle() {
	
	}
	
	public void setModuleTitle(string aModuletitle) {
	
	}
	
	public string getModuleTutor() {
	
	}
	
	public void setModuleTutor(string aModuletutor) {
	
	}
	
	public string getCourseWorkTitle() {
	
	}
	
	public void setCourseWorkTitle(string aCourseworktitle) {
	
	}
	
	public string getAssessmentType() {
	
	}
	
	public void setAssessemtType(string aAssessmentType) {
	
	}
}
