//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkList.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//
import java.util.ArrayList;



public class CourseWorkList {// creates the lists of coursework
	ArrayList<CourseWorkInfo> CourseWork = new ArrayList<CourseWorkInfo>();
        ArrayList<CourseWorkInfoInt> CourseWorkInt = new ArrayList<CourseWorkInfoInt>();
        private int refCount = -1; //set the refrence count to -1 i.e. not found
        CourseWorkInfoRepoImpl rep = new CourseWorkInfoRepoImpl();

	public void addNewCourseWork(String ModuleCode,String ModuleTitle,String ModuleTutor,String CourseWorkTitle,String AssessmentType,int CourseWorkNo,int IssueDate,int dueDate,int PerofMod) {
        CourseWorkInfo info = new CourseWorkInfo();
        CourseWorkInfoInt intinfo = new CourseWorkInfoInt();
        refCount++;
        info.setModuleCode(ModuleCode);
        info.setModuleTitle(ModuleTitle);
        info.setModuleTutor(ModuleTutor);
        info.setCourseWorkTitle(CourseWorkTitle);
        info.setAssessmentType(AssessmentType);
        intinfo.setCourseWorkNo(CourseWorkNo);
        intinfo.setIssueDate(IssueDate);
        intinfo.setDueDate(dueDate);
        intinfo.setPerofMod(PerofMod);
        intinfo.setID(refCount);
        rep.addCourseWork(info);
        rep.addCourseWorkInt(intinfo);
// this code just generates a new entity of CourseWorkInfo and CourseWorkInfoInt and sets the variables.
	}
	
	public void viewCourseWorks(int ID) {
            if (findCourseWorkInfo(ID)!= -1){
                CourseWorkInfo nome1 = rep.getCourseWork(ID);
                CourseWorkInfoInt nome2 = rep.getCourseWorkInt(ID);
                System.out.println("ModuleCode:"+nome1.getModuleCode());
                System.out.println("Moduel Title:"+nome1.getModuleTitle());
                System.out.println("Moduel Tutor:"+nome1.getModuleTutor());
                System.out.println("Course Work Title:"+nome1.getCourseWorkTitle());
                System.out.println("Assement Type:"+nome1.getAssessmentType());
                System.out.println("Course Work Number:"+nome2.getCourseWorkNo());
                System.out.println("Issue Date:"+nome2.getIssueDate());
                System.out.println("Due Date:"+nome2.getDueDate());
                System.out.println("Percentage of marks:"+nome2.getPerofMod());
                System.out.println("ID:"+nome2.getID());
            //out puts a specific CourseWork Info if found
            }
          
    }

        
        public void deleteCourseWorks(int Ref){ //not implimented but would delete a CourseWork
            
        }
        public void CourseWorkLists(){ //lists all CourseWork ID when implemented
            
        }
        public int findCourseWorkInfo (int ref) { //find if a Course Work exists
        for(CourseWorkInfoInt nome:rep.getAllCourseWorkInt()){
            if (nome.getID()==ref){
            return nome.getID();
        }
        }
        return -1;
    }
}
