//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkList.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkList {
	private List Coursework;
	public void addNewCourseWork(CourseWorkInfo NewCoursework) {
	
	}
	
	public void viewCourseWork(string Ref) {
	
	}
	
	public void findCourseWork(string Ref) {
	
	}
}
