//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information CourseWorkInfoRepo.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class CourseWorkInfoRepo {
	public void addCourseWork() {
	
	}
	
	public list viewAllCourseWork() {
	
	}
	
	public CourseWorkInfo ViewACourseWork(int ref) {
	
	}
	
	public void updateCourseWork() {
	
	}
	
	public void deleteCourseWork() {
	
	}
}
