//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information StaffAgent.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class StaffAgent {
	private List CourseworkList;
	public void createNewCourseWork(CourseWorkList list) {
	
	}
	
	public void deleteCourseWork(CouseWorkList list, string ID) {
	
	}
	
	public void viewCourseWork(customerList list, String ID) {
	
	}
}
