//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information StaffUI.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class StaffUI {
	private StaffAgent Control;
}
