//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project :340CT Untitled
//  @ File Name :Courseo Information StaffAgent.java
//  @ Date :22/11/2016 22/11/2016
//  @ Author :Toby Marshall 
//
//




public class StaffAgent { //makes the list that makes the lists of entities
	 private CourseWorkList list = new CourseWorkList();
         int CourseWorkNo  ;
         int IssueDate ;
         int dueDate ;
         int PerofMod;
         String ModuleCode;
         String ModuleTitle;
         String ModuleTutor ;
         String CourseWorkTitle ;
         String AssessmentType ;  
	public void createNewCourseWork(String ModuleCode,String ModuleTitle,String ModuleTutor,String CourseWorkTitle,String AssessmentType,int CourseWorkNo,int IssueDate,int dueDate,int PerofMod) {
	list.addNewCourseWork(ModuleCode,ModuleTitle,ModuleTutor,CourseWorkTitle,AssessmentType,CourseWorkNo,IssueDate,dueDate,PerofMod);
	}
	
	public void deleteCourseWork(int ID) {
	list.deleteCourseWorks(ID);
	}
	
	public void viewCourseWork(int ID) {
	list.viewCourseWorks(ID);
	}
        
        public void listAllCourseWork(){
                list.CourseWorkLists();
        }
       
        
}
